FROM node:10.7

ENV APP_ROOT /src
ENV HOST 0.0.0.0

RUN mkdir ${APP_ROOT}
WORKDIR ${APP_ROOT}

ARG CMD_YARN_VERSION=1.13.0
RUN npm install --global yarn@$CMD_YARN_VERSION @vue/cli @vue/cli-init

COPY . ${APP_ROOT}
RUN yarn
#CMD ["yarn" "run" "dev"]
